default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: remind_development

test:
  <<: *default
  database: remind_test

production:
  primary: &primary_production
    <<: *default
    database: remind_production
    username: railsapps
    password: <%= Rails.application.credentials.dig(:production, :database_password) %>
  cache:
    <<: *primary_production
    database: remind_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: remind_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: remind_production_cable
    migrations_paths: db/cable_migrate
